import { relations } from "drizzle-orm";
import { int, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

import { user } from "./auth";
import { divisionPolicy, tournamentDivision } from "./division-policy";
import { eventEntry, startingListEntry, startingListLock, tournamentRegistrationLock } from "./event-entry";
import { organization } from "./organization";
import { tournamentMembership } from "./tournament-membership";

export const tournament = sqliteTable("tournaments", {
  id: int().primaryKey({ autoIncrement: true }),
  organizationId: text("organization_id")
    .references(() => organization.id, { onDelete: "cascade" }),
  name: text().notNull().unique(),
  slug: text().notNull().unique(),
  description: text(),
  websiteUrl: text("website_url"),
  paymentInformation: text("payment_information"),
  facilities: text(),
  country: text(),
  city: text(),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  directorName: text("director_name"),
  directorEmail: text("director_email"),
  directorPhone: text("director_phone"),
  contactUserId: text("contact_user_id").references(() => user.id, { onDelete: "set null" }),
  lat: real().notNull(),
  long: real().notNull(),
  startDate: integer(),
  endDate: int(),
  registrationOpenDate: integer("registration_open_date"),
  registrationCloseDate: integer("registration_close_date"),
  closedAt: int("closed_at"),
  isSanctioned: int("is_sanctioned", { mode: "boolean" }).notNull().default(false),
  divisionOpen: int("division_open", { mode: "boolean" }).notNull().default(true),
  divisionWomen: int("division_women", { mode: "boolean" }).notNull().default(true),
  divisionMaster: int("division_master", { mode: "boolean" }).notNull().default(false),
  divisionGrandMaster: int("division_grand_master", { mode: "boolean" }).notNull().default(false),
  divisionSeniorGrandMaster: int("division_senior_grand_master", { mode: "boolean" }).notNull().default(false),
  divisionLegend: int("division_legend", { mode: "boolean" }).notNull().default(false),
  divisionJunior: int("division_junior", { mode: "boolean" }).notNull().default(false),
  keepJuniorsSeparate: int("keep_juniors_separate", { mode: "boolean" }).notNull().default(false),
  showDivisionInResults: int("show_division_in_results", { mode: "boolean" }).notNull().default(false),
  hasGolf: int({ mode: "boolean" }),
  golfRounds: integer("golf_rounds"),
  golfCumulativeRounds: integer("golf_cumulative_rounds"),
  hasAccuracy: integer({ mode: "boolean" }),
  accuracyRounds: integer("accuracy_rounds"),
  accuracyCumulativeRounds: integer("accuracy_cumulative_rounds"),
  hasDistance: integer({ mode: "boolean" }),
  distanceRounds: integer("distance_rounds"),
  distanceCumulativeRounds: integer("distance_cumulative_rounds"),
  hasSCF: integer({ mode: "boolean" }),
  scfRounds: integer("scf_rounds"),
  scfCumulativeRounds: integer("scf_cumulative_rounds"),
  hasDiscathon: integer({ mode: "boolean" }),
  discathonRounds: integer("discathon_rounds"),
  discathonCumulativeRounds: integer("discathon_cumulative_rounds"),
  hasDDC: integer({ mode: "boolean" }),
  ddcRounds: integer("ddc_rounds"),
  ddcCumulativeRounds: integer("ddc_cumulative_rounds"),
  hasFreestyle: integer({ mode: "boolean" }),
  freestyleRounds: integer("freestyle_rounds"),
  freestyleCumulativeRounds: integer("freestyle_cumulative_rounds"),
  banRequestEmailEnabled: int("ban_request_email_enabled", { mode: "boolean" }).notNull().default(true),
  changedBy: int().notNull().references(() => user.id),
  createdAt: int().notNull().$default(() => Date.now()),
  changedAt: int().notNull().$default(() => Date.now()).$onUpdate(() => Date.now()),
});

export const tournamentRelations = relations(tournament, ({ one, many }) => ({
  organization: one(organization, {
    fields: [tournament.organizationId],
    references: [organization.id],
  }),
  memberships: many(tournamentMembership),
  divisionPolicies: many(divisionPolicy),
  offeredDivisions: many(tournamentDivision),
  eventEntries: many(eventEntry),
  startingListEntries: many(startingListEntry),
  startingListLocks: many(startingListLock),
  registrationLocks: many(tournamentRegistrationLock),
}));
